I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 190, in script
    python:
  File "renpy/common/00start.rpy", line 191, in <module>
    renpy.execute_default_statement(True)
  File "game/script.rpy", line 30, in set_default
    default scache = Scenecache()
  File "game/script.rpy", line 30, in <module>
    default scache = Scenecache()
TypeError: __init__() takes exactly 2 arguments (1 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 190, in script
    python:
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 191, in <module>
    renpy.execute_default_statement(True)
  File "renpy/exports.py", line 3590, in execute_default_statement
    i.set_default(start)
  File "game/script.rpy", line 30, in set_default
    default scache = Scenecache()
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 30, in <module>
    default scache = Scenecache()
TypeError: __init__() takes exactly 2 arguments (1 given)

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
FX 1.0
Thu Jun  3 11:50:29 2021
